---
abstract: 'Expose a DBIC QueryLog Instance in Middleware'
author:
  - 'John Napiorkowski, C<< <jjnapiork@cpan.org> >>'
build_requires:
  Data::Dump: 0
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::Common: 0
  Scalar::Util: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::DBIC::QueryLog
name: Plack-Middleware-DBIC-QueryLog
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class::QueryLog: 1.3.0
  Moo: 0.009004
  Plack: 0.9957
resources:
  homepage: http://search.cpan.org/dist/Plack-Middleware-DBIC-QueryLog/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/Plack-Middleware-DBIC-QueryLog.git
version: 0.01
